package constants

const DATABASE_TYPE = "DATABASE_TYPE"
const DATABASE_HOST = "DATABASE_HOST"
const DATABASE_PORT = "DATABASE_PORT"
const DATABASE_USER = "DATABASE_USER"
const DATABASE_PASSWORD = "DATABASE_PASSWORD"

const STORAGE_TYPE = "STORAGE_TYPE"
const STORAGE_ENDPOINT = "STORAGE_ENDPOINT"
const STORAGE_ACCESSKEY = "STORAGE_ACCESSKEY"
const STORAGE_SECRETKEY = "STORAGE_SECRETKEY"
const STORAGE_BUCKET = "STORAGE_BUCKET"

const NOTIFICATION_TYPE = "NOTIFICATION_TYPE"
const SLACK_WEBHOOK_URL = "SLACK_WEBHOOK_URL"